#!/bin/sh
set -e

sed -i 's|##SERVERADMIN##|${SERVERADMIN}|' /usr/local/apache2/conf/httpd.conf
sed -i 's|##DESTINATION##|${DESTINATION}|' /usr/local/apache2/conf/httpd.conf

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

exec httpd -DFOREGROUND "$@"
